### ISSUE TITLE
Won't work on Windows 10 w/ 2 Screens

### ISSUE THREAD

**Issue by lordfiSh** [FireEmerald/Settlers4-Widescreen-Tool#1]
started it with Compatibility mode, game switches resolution a few times and starts on 2nd Monitor with like 320x480, cant move mouse.

**Comment by FireEmerald** [comment]
Which Version of the Settlers do you use?

**Comment by lordfiSh** [comment]
THE SETTLERS IV GOLD Version 2.0.0.4 from GOG. The Game starts only with compatibility mode, maybe it's just not compatible with Windows 10... 

and you should swap the Apply and Start Button ;)

**Comment by FireEmerald** [comment]
The version number "2.0.0.4" is taken from the first screen ingame, correct?
Then you should patch your game, because i have here Version *2.50.1508*.

**Comment by lordfiSh** [comment]
Sry it's 2.50.1516 - 2.0.0.4 in the GOG Filename.
Game works "fine" on Windows 10 as long I start it with compatibility mode and chose "Run in 640x480"

If I start it without, the Game take only ~1/4 of the Screen but you cant use the Mouse, your App don't change that. Maybe I have to use a VM with Windows 7 to play the Game...

**Comment by FireEmerald** [comment]
It seems like Windows 10 doesn't like S4 - especially if you run it in a VM:
![2015-12-23 17_12_54-win10_pro_64bit wird ausgefuhrt - oracle vm virtualbox _ 1](https://cloud.githubusercontent.com/assets/1107939/11980105/9a01cd22-a998-11e5-999f-be0ac80cb7ab.png)

**Comment by FireEmerald** [comment]
@lordfiSh I swapped the Apply and Start Button, as you proposed. I also added some extra checks and a note for the Windows 8+ compatibility.

**Comment by lordfiSh** [comment]
Thanks :+1: 

As I said the Game works with compatibility mode and chose "Run in 640x480", but as it seems not with more than that at Windows 10 :(

**Comment by FireEmerald** [comment]
Yep, your problem is that the game doesn't run in higher resolutions, but i tried to install S4 now on my "real" Windows 10 System and the installation process doesn't start at all :D
