### ISSUE TITLE
Game crashes after patching

### ISSUE THREAD

**Issue by LONGACAT** [FireEmerald/Settlers4-Widescreen-Tool#10]
**Details:**
**OS:** Windows 7 Ultimate
**Game:** GOG 2.50.1516
**Patch resolution:** 1280x800

After I patched the game, resolution stayed at 800x600. Manual patch (replacing the DLL) did nothing as well. When I tried to change resolution to option 1024x768 (which I assume is the patched one) the game crashed with error: Exception 0xc0000005 at 0x18c2fc0e. Now, after running the game and launching any mission I get the crash. 

Is there a way that I can play at 1280x800? (If I replace the DLL back to default, it doesn't crash and runs on 1024x768)

**Comment by FireEmerald** [comment]
> When I tried to change resolution to option 1024x768 the game crashed...
Ingame? Do **not** change the resolution ingame - just replace the dll.

**Comment by LONGACAT** [comment]
The resolution stays at 800x600 then, even after replacing the DLL

**Comment by FireEmerald** [comment]
Ok, that's strange. Could you try to save your savegames (`/save` directory) and then reinstall the game to try it with a blank system? Make sure everything is deleted.

**Comment by LONGACAT** [comment]
I re-installed the game. 
1. Checked if the game works without patch: It does
2. Patched the game
3. Checked if the game does work with the patch: No. Exception 0xc0000005 at 0x18c2fc0e

**Comment by FireEmerald** [comment]
I downloaded the latest installer from GOG: `setup_the_settlers_4_gold_2.50.1516_v2_(30536).exe`

After setting the resolution to 1920x1080 the game runs fine on Windows 10. I could not reproduce your issue.

The selected resolution must be equal to your desktop resolution. I don't think that you have a screen which is 1280x800, aren't you? Another problem could be Win 7 or your graphics drivers.

**Comment by LONGACAT** [comment]
I do have a 1280x800 screen, both Windows 7 and Linux report it as such, as well as the manufacturer.
I think it's more of graphics drivers problem, as this a laptop with integrated graphics.
