### ISSUE TITLE
S4.exe is not available

### ISSUE THREAD

**Issue by Michilliv** [FireEmerald/Settlers4-Widescreen-Tool#11]
Hey,

i tried to use your widescreen tool, but I have a problemselecting the files.
The original Game .exe is named S4_Main, so i changed it to S4.exe. This worked so i was able to select it. But after that the tool does not find the other files ("<InstallDir>\Config\GameSettings.cfg or <InstallDir>\Exe\GfxEngine.dll doesn't exist!")
But it's there, it's on this location C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\thesettlers4\Config\GameSettings.cfg

Do you know what's the error?

Michael

**Comment by adrianer** [comment]
This tool is for the "classic" S4 edition (on a CD or GoG-version). You are trying to use it with the History Edition (HE): it's not needed for that version, because HE already supports wide screens.

**Comment by Michilliv** [comment]
Oh ok, thanks for the quick answer. Maybe I had some configuration errors.
