### ISSUE TITLE
[feature request] Inverting scroll direction.

### ISSUE THREAD

**Issue by jacekmigacz** [FireEmerald/Settlers4-Widescreen-Tool#2]
Would be great to swap scroll axes to achieve natural scrolling direction.

**Comment by FireEmerald** [comment]
Do you mean the Y-axis of the "**3. Log**" text box?
![2016-12-19 20_26_35-the settlers 4_ widescreen tool](https://cloud.githubusercontent.com/assets/1107939/21326084/7e648fe2-c629-11e6-8efa-746102fcef9b.png)

The scroll behavior is the same as in the windows explorer.

**Comment by jacekmigacz** [comment]
I meant both X-axis and Y-axis to achieve user experience similar to Google Maps. 
Right-Mouse-Button and move to bottom-right would scroll up-left.

**Comment by FireEmerald** [comment]
Well, the text box doesn't have a scroll bar for the X-axis. This one is disabled. If the text get's to long, there will be a word wrap. And for the Y-axis - as i said - the behavior is the same as in the windows explorer. Google Maps is a web based application and has nothing to do with a text box of windows form's so i will let the scrolling direction how it is at the moment ;) Anyways, thanks for your suggestion.

**Comment by jacekmigacz** [comment]
Hi. I've just realized we are talking about different things.
I was thinking about **in-game** scrolling. Not about tool's UI.
In these days the way the Settlers 4 scrolls is counter-intuitive.
I thought if you have already spent some time analyzing S4.exe binary, maybe you could modify that.
